name: Push public files to another repo

on:
  push:
    branches:
      - develop
  
jobs:
  push:
    name: Push public files to public repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: re-initialize repo
        shell: bash
        id: git-status
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          export git_message=$(git log -1 --pretty=%B)
          echo $git_message
          rm -r .git
          git init
          echo -e "\n" >> .gitignore
          cat .gitignore.public >> .gitignore
          git status
          cat .gitignore
          git add --all
          git status
          git commit -m "$git_message"
          git status
