name: Push public files to another repo

on:
  push:
    branches:
      - develop
  
jobs:
  push:
    name: Push public files to public repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: re-initialize repo
        shell: bash
        id: git-status
        run: | 
          rm -r .git
          git init
          cat .gitignore.public >> .gitignore
          git status
          cat .gitignore


        