name: Push public files to another repo

on:
  push:
    branches:
      - develop
  
jobs:
  name: Push public files to public repo
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: list files
      shell: bash
      run: git status
      id: git-status
